# Generated by Django 6.1 on 2026-08-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Duración en horas'),
        ),
    ]
